---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-demo
    app.kubernetes.io/version: "8.2"
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wp-data-storage
          persistentVolumeClaim:
            claimName: wp-data-claim
      containers:
        - name: wordpress
          image: ghcr.io/farghul/php:fpm-k8s
          ports:
          - containerPort: 9000
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "300m"
              memory: "600Mi"
          volumeMounts:
            - mountPath: /var/www/html
              name: wp-data-storage
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
...
