---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-data-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"
...
