---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
...
