---
- name: Build, tag, and push Podman images
  hosts: darwin
  connection: local
  vars_files: defaults/main.yaml
  gather_facts: false
  tasks:
    - name: Build the MariaDB image
      tags: mdb
      block:
        - name: Build the MariaDB image
          ansible.builtin.command:
            chdir: "{{ SELF }}/podman/mariadb"
            cmd: podman build --file Containerfile --tag mariadb . --no-cache

        - name: Tag the MariaDB build
          ansible.builtin.command: podman image tag mariadb:latest {{ MARIADB }}

        - name: Push the MariaDB build to a container registry
          ansible.builtin.command: podman push {{ MARIADB }}
      rescue:
        - name: Make sure all handlers run
          meta: flush_handlers

    - name: Build the PHP image
      tags: php
      block:
        - name: Build the PHP image
          ansible.builtin.command:
            chdir: "{{ SELF }}/podman/php"
            cmd: podman build --file Containerfile --tag php --build-arg COMPOSER={{ COMPOSER }} . --no-cache

        - name: Tag the PHP build
          ansible.builtin.command: podman image tag php:latest {{ PHP }}

        - name: Push the PHP build to a container registry
          ansible.builtin.command: podman push {{ PHP }}
      rescue:
        - name: Make sure all handlers run
          meta: flush_handlers

    - name: Build the NGiNX image
      tags: nginx
      block:
        - name: Build the NGiNX image
          ansible.builtin.command:
            chdir: "{{ SELF }}/podman/nginx"
            cmd: podman build --file Containerfile --tag nginx . --no-cache

        - name: Tag the NGiNX build
          ansible.builtin.command: podman image tag nginx:latest {{ NGiNX }}
          
        - name: Push the NGiNX build to a container registry
          ansible.builtin.command: podman push {{ NGiNX }}
      rescue:
        - name: Make sure all handlers run
          meta: flush_handlers
  handlers:
    - name: Run me even after an error
      ansible.builtin.debug:
        msg: 'This handler runs even on error'
...
